name = "dataset-splitter-worker"
main = "src/index.js"
compatibility_date = "2026-03-17"

# This links  worker to R2 bucket
[[r2_buckets]]
binding = "MY_BUCKET" #this is how i call it
bucket_name = "veralabel-datasets"

[vars]
# Node.js backend URL for the webhooks
BACKEND_API = "https://api.veralabel.ai/v1/internal/register-task"